@startuml Communication Design
participant Client as cl
participant Server as sv

group game start
cl -> sv: Post Game request
sv -> cl: Response with game details


cl -> sv: Get Game state
sv -> cl: Response Game state

cl -> sv: Post Move
sv -> cl: Response Code and/or Game state

@enduml